version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:latest
    working_directory: ~/iron-truck
    steps:
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: repo-{{ checksum ".circle-sha" }}
          paths:
            - ~/jobs
  test:
    docker:
      - image: circleci/node:latest
    working_directory: ~/iron-truck
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          key: repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/iron-truck/node_modules
      - run:
          name: test
          command: |
            npm test

  # deploy:
  #   docker:
  #     - image: circleci/node:latest
  #   working_directory: ~/jobs
  #   steps:
  #     - restore_cache:
  #         key: repo-{{ checksum ".circle-sha" }}
  #     - restore_cache:
  #         key: dependency-cache-{{ checksum "package.json" }}
  #     - deploy:
  #         name: Deploy
  #         command: |
  #           if [ "${CIRCLE_BRANCH:-}" = "master" ]; then
  #             npm install -g serverless
  #             npm install -g serverless-azure-functions
  #             serverless deploy function -f localTrucks
  #           fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
      # - deploy:
      #     requires:
      #       - test